FROM alpine:latest

RUN apk update && \
    apk add --no-cache openssh-client

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

COPY docker/ssh-entrypoint.sh /usr/local/bin/ssh-entrypoint.sh
RUN chmod +x /usr/local/bin/ssh-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/ssh-entrypoint.sh"]
