version: '3.8'

services:
  ssh_tunnel:
    build:
      context: .
      dockerfile: dockerfile.ssh
    container_name: ssh_tunnel_planka
    restart: unless-stopped
    volumes:
      - ${SSH_PRIVATE_KEY_PATH:-./ipelabor.key}:/run/ssh-keys/ipelabor.key:ro
    environment:
      SSH_REMOTE_USER: ${SSH_REMOTE_USER}
      SSH_REMOTE_HOST: ${SSH_REMOTE_HOST}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-22}
      SSH_TUNNEL_REMOTE_PORT: ${SSH_TUNNEL_REMOTE_PORT:-7004}
      SSH_TUNNEL_TARGET_HOST: ${SSH_TUNNEL_TARGET_HOST:-planka}
      SSH_TUNNEL_TARGET_PORT: ${SSH_TUNNEL_TARGET_PORT:-1337}
    depends_on:
      planka:
        condition: service_started

  postgres_server:
    image: postgres:18.3
    container_name: postgres_server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PLANKA_PROD_DATABASE_USER}
      POSTGRES_PASSWORD: ${PLANKA_PROD_DATABASE_PASSWORD}
      POSTGRES_DB: ${PLANKA_PROD_DATABASE_DB}
    volumes:
      - pg18_data:/var/lib/postgresql
    ports:
      - 7432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PLANKA_PROD_DATABASE_USER} -d ${PLANKA_PROD_DATABASE_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  planka:
    container_name: planka
    build:
      context: .
      dockerfile: Dockerfile
    image: ipelabor/planka:2.1.1-ipelabor.1
    restart: on-failure
    volumes:
      - data:/app/data
      - favicons:/app/data/protected/favicons
      - user-avatars:/app/data/protected/user-avatars
      - background-images:/app/data/protected/background-images
      - attachments:/app/data/private/attachments
      - ./terms:/app/terms/custom
    ports:
      - 7004:1337
    environment:
      BASE_URL: ${PLANKA_PROD_BASE_URL}
      DATABASE_URL: postgresql://${PLANKA_PROD_DATABASE_USER}:${PLANKA_PROD_DATABASE_PASSWORD}@postgres_server:5432/${PLANKA_PROD_DATABASE_DB}
      SECRET_KEY: ${PLANKA_PROD_SECRET_KEY}
      DEFAULT_ADMIN_EMAIL: ${PLANKA_DEFAULT_ADMIN_EMAIL}
      DEFAULT_ADMIN_PASSWORD: ${PLANKA_DEFAULT_ADMIN_PASSWORD}
      DEFAULT_ADMIN_NAME: ${PLANKA_DEFAULT_ADMIN_NAME}
      DEFAULT_ADMIN_USERNAME: ${PLANKA_DEFAULT_ADMIN_USERNAME}
      SMTP_HOST: ${PLANKA_SMTP_HOST}
      SMTP_PORT: ${PLANKA_SMTP_PORT}
      SMTP_NAME: ${PLANKA_SMTP_NAME}
      SMTP_SECURE: ${PLANKA_SMTP_SECURE}
      SMTP_TLS_REJECT_UNAUTHORIZED: ${PLANKA_SMTP_TLS_REJECT_UNAUTHORIZED}
      SMTP_USER: ${PLANKA_SMTP_USER}
      SMTP_PASSWORD: ${PLANKA_SMTP_PASSWORD}
      SMTP_FROM: ${PLANKA_SMTP_FROM}
    depends_on:
      postgres_server:
        condition: service_healthy

volumes:
  pg18_data:
  data:
  favicons:
  user-avatars:
  background-images:
  attachments:
